baseURL = 'http://example.org/'
languageCode = 'fr'
title = 'Blohorn Agar'
theme = 'ananke'
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true
contentDir = 'content'
publishDir = 'public'


[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"


[params]
text_color = ""
author = ''
AuthorName = 'Blohorn Agar'
favicon = ""
site_logo = "images/Mf.png"
description = "Data is power"
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-blue"
recent_posts_number = 3

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/agarblohorn/"
